apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:              
    app: wordpress       #Deployment labels should match to this selectors
    tier: frontend
  type: LoadBalancer     #loadbalancer will be created by auto if we use cloud(for us GCP)
