apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-deploy
spec:
  selector:
    matchLabels:
      app: init-deploy
  template:
    metadata:
      labels:
        app: init-deploy
    spec:
      volumes:
        - name:  shared-to-actual
          emptyDir: {}  
      initContainers:
      - name: init-busybox-container
        image: busybox
        volumeMounts:
          - name: shared-to-actual
            mountPath: /data
        command: ["/bin/sh"]
        args: ["-c", "echo '<h1>Welcome to InitContiner</h1>' > /data/index.html"]
      containers:
      - name: actual-nginx-container
        image: nginx
        volumeMounts:
        - name:  shared-to-actual
          mountPath:  /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: init-service
spec:
  selector:
    app: init-deploy
  ports:
  - port: 80
    targetPort: 80
    name:  service-port
  type: NodePort
