apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: custom-sc-pd-standard     # custom sc for dynamic provisioning and this should exists prior storageClassName of pvc
  accessModes:
    - ReadWriteOnce    
  resources:
    requests:
      storage: 10Gi