apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress #label of selector to use, ex: mysql-service
        tier: frontend #label of selector to use, ex: mysql-service
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST          #Custom env key/value pair will be used for container directly not using configMap
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD  
          valueFrom:
            secretKeyRef:                  #Password retrive from secret
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-pvc           #Should match wp-pvc.yaml metadata name       